"""cria categorias unidades medidas produtos e informacoes nutricionais

Revision ID: 5b3edfcad3ca
Revises: 6f4bcb558645
Create Date: 2026-08-27 13:38:47.009376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b3edfcad3ca'
down_revision: Union[str, Sequence[str], None] = '6f4bcb558645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('unidades_medidas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('sigla', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('informacoes_nutricionais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('porcao_quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_energetico_kcal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('carboidratos_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('proteinas_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gorduras_totais_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ingredientes', sa.Text(), nullable=True),
    sa.Column('alergenicos', sa.Text(), nullable=True),
    sa.Column('id_unidade_porcao', sa.Integer(), nullable=False),
    sa.CheckConstraint('carboidratos_g >= 0', name='ck_in_carboidratos'),
    sa.CheckConstraint('gorduras_totais_g >= 0', name='ck_in_gorduras_totais'),
    sa.CheckConstraint('porcao_quantidade > 0', name='ck_in_porcao_quantidade'),
    sa.CheckConstraint('proteinas_g >= 0', name='ck_in_proteinas'),
    sa.CheckConstraint('valor_energetico_kcal >= 0', name='ck_in_valor_energetico'),
    sa.ForeignKeyConstraint(['id_unidade_porcao'], ['unidades_medidas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cod_idt', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_venda_atual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id_funcionario', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('id_unidade_medida', sa.Integer(), nullable=False),
    sa.Column('id_inf_nut', sa.Integer(), nullable=True),
    sa.CheckConstraint('preco_venda_atual >= 0', name='ck_produto_preco_venda'),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['id_funcionario'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['id_inf_nut'], ['informacoes_nutricionais.id'], ),
    sa.ForeignKeyConstraint(['id_unidade_medida'], ['unidades_medidas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_idt'),
    sa.UniqueConstraint('nome')
    )
    op.create_index('idx_produto_id_categoria', 'produtos', ['id_categoria'], unique=False)
    op.create_index('idx_produto_id_funcionario', 'produtos', ['id_funcionario'], unique=False)
    op.create_index('idx_produto_id_unidade_medida', 'produtos', ['id_unidade_medida'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_produto_id_unidade_medida', table_name='produtos')
    op.drop_index('idx_produto_id_funcionario', table_name='produtos')
    op.drop_index('idx_produto_id_categoria', table_name='produtos')
    op.drop_table('produtos')
    op.drop_table('informacoes_nutricionais')
    op.drop_table('unidades_medidas')
    op.drop_table('categorias')
    # ### end Alembic commands ###
