"""cria lotes entradas estoques e saidas

Revision ID: 6927cfe11206
Revises: 5b3edfcad3ca
Create Date: 2026-08-27 14:15:24.436808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6927cfe11206'
down_revision: Union[str, Sequence[str], None] = '5b3edfcad3ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_produto', 'numero', name='un_lote_produto_numero')
    )
    op.create_index('idx_lote_data_validade', 'lotes', ['data_validade'], unique=False)
    op.create_index('idx_lote_numero', 'lotes', ['numero'], unique=False)
    op.create_table('entradas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_entrada', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('preco_custo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_fornecedor', sa.Integer(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.CheckConstraint('preco_custo_unitario >= 0', name='ck_entrada_preco_custo'),
    sa.CheckConstraint('quantidade > 0', name='ck_entrada_quantidade'),
    sa.ForeignKeyConstraint(['id_fornecedor'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['id_lote'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entrada_data_entrada', 'entradas', ['data_entrada'], unique=False)
    op.create_index('idx_entrada_fornecedor_data', 'entradas', ['id_fornecedor', 'data_entrada'], unique=False)
    op.create_index('idx_entrada_id_fornecedor', 'entradas', ['id_fornecedor'], unique=False)
    op.create_index('idx_entrada_id_lote', 'entradas', ['id_lote'], unique=False)
    op.create_table('estoques',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantidade_atual', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('corredor', sa.String(length=30), nullable=False),
    sa.Column('prateleira', sa.String(length=30), nullable=False),
    sa.Column('secao', sa.String(length=30), nullable=False),
    sa.Column('id_entrada', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantidade_atual >= 0', name='ck_estoque_quantidade'),
    sa.ForeignKeyConstraint(['id_entrada'], ['entradas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_estoque_id_entrada', 'estoques', ['id_entrada'], unique=False)
    op.create_table('saidas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_saida', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('preco_venda_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id_estoque', sa.Integer(), nullable=False),
    sa.Column('tipo_saida', sa.Enum('VENDA', 'PERDA', 'AVARIA', 'VENCIMENTO', 'RECALL', name='tiposaidaenum', native_enum=False, length=30), nullable=False),
    sa.CheckConstraint("\n            (\n                tipo_saida = 'VENDA'\n                AND preco_venda_unitario IS NOT NULL\n            )\n            OR\n            (\n                tipo_saida <> 'VENDA'\n                AND preco_venda_unitario IS NULL\n            )\n            ", name='ck_saida_preco'),
    sa.CheckConstraint("\n            tipo_saida IN (\n                'VENDA',\n                'PERDA',\n                'AVARIA',\n                'VENCIMENTO',\n                'RECALL'\n            )\n            ", name='ck_saida_tipo'),
    sa.CheckConstraint('quantidade > 0', name='ck_saida_quantidade'),
    sa.ForeignKeyConstraint(['id_estoque'], ['estoques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_saida_data_saida', 'saidas', ['data_saida'], unique=False)
    op.create_index('idx_saida_id_estoque', 'saidas', ['id_estoque'], unique=False)
    op.create_index('idx_saida_tipo_data', 'saidas', ['tipo_saida', 'data_saida'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_saida_tipo_data', table_name='saidas')
    op.drop_index('idx_saida_id_estoque', table_name='saidas')
    op.drop_index('idx_saida_data_saida', table_name='saidas')
    op.drop_table('saidas')
    op.drop_index('idx_estoque_id_entrada', table_name='estoques')
    op.drop_table('estoques')
    op.drop_index('idx_entrada_id_lote', table_name='entradas')
    op.drop_index('idx_entrada_id_fornecedor', table_name='entradas')
    op.drop_index('idx_entrada_fornecedor_data', table_name='entradas')
    op.drop_index('idx_entrada_data_entrada', table_name='entradas')
    op.drop_table('entradas')
    op.drop_index('idx_lote_numero', table_name='lotes')
    op.drop_index('idx_lote_data_validade', table_name='lotes')
    op.drop_table('lotes')
    # ### end Alembic commands ###
