"""cria enderecos usuarios fornecedores e contatos

Revision ID: 6f4bcb558645
Revises: 001
Create Date: 2026-08-27 12:56:15.911803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4bcb558645'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contatos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cod_pais', sa.String(length=30), nullable=False),
    sa.Column('ddd', sa.String(length=3), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_pais', 'ddd', 'numero', name='un_contato_telefone')
    )
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('logradouro', sa.String(length=50), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('complemento', sa.String(length=50), nullable=True),
    sa.Column('cep', sa.String(length=11), nullable=False),
    sa.Column('bairro', sa.String(length=30), nullable=False),
    sa.Column('id_municipio', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_municipio'], ['cidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('cnpj', sa.CHAR(length=14), nullable=False),
    sa.Column('id_endereco', sa.Integer(), nullable=False),
    sa.Column('id_contato', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_contato'], ['contatos.id'], ),
    sa.ForeignKeyConstraint(['id_endereco'], ['enderecos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('nivel_acesso', sa.Enum('administrador', 'operador', name='nivel_acesso_enum'), nullable=False),
    sa.Column('id_endereco', sa.Integer(), nullable=False),
    sa.Column('id_contato', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_contato'], ['contatos.id'], ),
    sa.ForeignKeyConstraint(['id_endereco'], ['enderecos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_contato')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funcionarios')
    op.drop_table('fornecedores')
    op.drop_table('enderecos')
    op.drop_table('contatos')
    # ### end Alembic commands ###
